# Generated by Django 2.1.1 on 2018-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_like_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_total',
            field=models.IntegerField(default=0),
        ),
    ]
